//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ChqPrint
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ChqDatabase1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ChqDatabase1Entities object using the connection string found in the 'ChqDatabase1Entities' section of the application configuration file.
        /// </summary>
        public ChqDatabase1Entities() : base("name=ChqDatabase1Entities", "ChqDatabase1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ChqDatabase1Entities object.
        /// </summary>
        public ChqDatabase1Entities(string connectionString) : base(connectionString, "ChqDatabase1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ChqDatabase1Entities object.
        /// </summary>
        public ChqDatabase1Entities(EntityConnection connection) : base(connection, "ChqDatabase1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cheques> Cheques
        {
            get
            {
                if ((_Cheques == null))
                {
                    _Cheques = base.CreateObjectSet<Cheques>("Cheques");
                }
                return _Cheques;
            }
        }
        private ObjectSet<Cheques> _Cheques;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Formatos> Formatos
        {
            get
            {
                if ((_Formatos == null))
                {
                    _Formatos = base.CreateObjectSet<Formatos>("Formatos");
                }
                return _Formatos;
            }
        }
        private ObjectSet<Formatos> _Formatos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admins> Admins
        {
            get
            {
                if ((_Admins == null))
                {
                    _Admins = base.CreateObjectSet<Admins>("Admins");
                }
                return _Admins;
            }
        }
        private ObjectSet<Admins> _Admins;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cheques EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCheques(Cheques cheques)
        {
            base.AddObject("Cheques", cheques);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Formatos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormatos(Formatos formatos)
        {
            base.AddObject("Formatos", formatos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmins(Admins admins)
        {
            base.AddObject("Admins", admins);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChqDatabase1Model", Name="Admins")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admins : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admins object.
        /// </summary>
        /// <param name="idAdmin">Initial value of the idAdmin property.</param>
        public static Admins CreateAdmins(global::System.Int32 idAdmin)
        {
            Admins admins = new Admins();
            admins.idAdmin = idAdmin;
            return admins;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAdmin
        {
            get
            {
                return _idAdmin;
            }
            set
            {
                if (_idAdmin != value)
                {
                    OnidAdminChanging(value);
                    ReportPropertyChanging("idAdmin");
                    _idAdmin = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idAdmin");
                    OnidAdminChanged();
                }
            }
        }
        private global::System.Int32 _idAdmin;
        partial void OnidAdminChanging(global::System.Int32 value);
        partial void OnidAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChqDatabase1Model", Name="Cheques")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cheques : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cheques object.
        /// </summary>
        /// <param name="idCheque">Initial value of the idCheque property.</param>
        /// <param name="nroCheque">Initial value of the nroCheque property.</param>
        public static Cheques CreateCheques(global::System.Int32 idCheque, global::System.String nroCheque)
        {
            Cheques cheques = new Cheques();
            cheques.idCheque = idCheque;
            cheques.nroCheque = nroCheque;
            return cheques;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCheque
        {
            get
            {
                return _idCheque;
            }
            set
            {
                if (_idCheque != value)
                {
                    OnidChequeChanging(value);
                    ReportPropertyChanging("idCheque");
                    _idCheque = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCheque");
                    OnidChequeChanged();
                }
            }
        }
        private global::System.Int32 _idCheque;
        partial void OnidChequeChanging(global::System.Int32 value);
        partial void OnidChequeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nroCheque
        {
            get
            {
                return _nroCheque;
            }
            set
            {
                OnnroChequeChanging(value);
                ReportPropertyChanging("nroCheque");
                _nroCheque = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nroCheque");
                OnnroChequeChanged();
            }
        }
        private global::System.String _nroCheque;
        partial void OnnroChequeChanging(global::System.String value);
        partial void OnnroChequeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private Nullable<global::System.Int32> _Monto;
        partial void OnMontoChanging(Nullable<global::System.Int32> value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PagueseOrdenDe
        {
            get
            {
                return _PagueseOrdenDe;
            }
            set
            {
                OnPagueseOrdenDeChanging(value);
                ReportPropertyChanging("PagueseOrdenDe");
                _PagueseOrdenDe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PagueseOrdenDe");
                OnPagueseOrdenDeChanged();
            }
        }
        private global::System.String _PagueseOrdenDe;
        partial void OnPagueseOrdenDeChanging(global::System.String value);
        partial void OnPagueseOrdenDeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MontoEnLetras
        {
            get
            {
                return _MontoEnLetras;
            }
            set
            {
                OnMontoEnLetrasChanging(value);
                ReportPropertyChanging("MontoEnLetras");
                _MontoEnLetras = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MontoEnLetras");
                OnMontoEnLetrasChanged();
            }
        }
        private global::System.String _MontoEnLetras;
        partial void OnMontoEnLetrasChanging(global::System.String value);
        partial void OnMontoEnLetrasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Banco
        {
            get
            {
                return _Banco;
            }
            set
            {
                OnBancoChanging(value);
                ReportPropertyChanging("Banco");
                _Banco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Banco");
                OnBancoChanged();
            }
        }
        private global::System.String _Banco;
        partial void OnBancoChanging(global::System.String value);
        partial void OnBancoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Talonario
        {
            get
            {
                return _Talonario;
            }
            set
            {
                OnTalonarioChanging(value);
                ReportPropertyChanging("Talonario");
                _Talonario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Talonario");
                OnTalonarioChanged();
            }
        }
        private global::System.String _Talonario;
        partial void OnTalonarioChanging(global::System.String value);
        partial void OnTalonarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String concepto
        {
            get
            {
                return _concepto;
            }
            set
            {
                OnconceptoChanging(value);
                ReportPropertyChanging("concepto");
                _concepto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("concepto");
                OnconceptoChanged();
            }
        }
        private global::System.String _concepto;
        partial void OnconceptoChanging(global::System.String value);
        partial void OnconceptoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChqDatabase1Model", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        public static Clientes CreateClientes(global::System.Int32 idCliente)
        {
            Clientes clientes = new Clientes();
            clientes.idCliente = idCliente;
            return clientes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                if (_idCliente != value)
                {
                    OnidClienteChanging(value);
                    ReportPropertyChanging("idCliente");
                    _idCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCliente");
                    OnidClienteChanged();
                }
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alias
        {
            get
            {
                return _Alias;
            }
            set
            {
                OnAliasChanging(value);
                ReportPropertyChanging("Alias");
                _Alias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alias");
                OnAliasChanged();
            }
        }
        private global::System.String _Alias;
        partial void OnAliasChanging(global::System.String value);
        partial void OnAliasChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChqDatabase1Model", Name="Formatos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Formatos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Formatos object.
        /// </summary>
        /// <param name="idFormato">Initial value of the idFormato property.</param>
        public static Formatos CreateFormatos(global::System.Int32 idFormato)
        {
            Formatos formatos = new Formatos();
            formatos.idFormato = idFormato;
            return formatos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFormato
        {
            get
            {
                return _idFormato;
            }
            set
            {
                if (_idFormato != value)
                {
                    OnidFormatoChanging(value);
                    ReportPropertyChanging("idFormato");
                    _idFormato = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idFormato");
                    OnidFormatoChanged();
                }
            }
        }
        private global::System.Int32 _idFormato;
        partial void OnidFormatoChanging(global::System.Int32 value);
        partial void OnidFormatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
    }

    #endregion
    
}
